### ISSUE TITLE
enhancement: support to create clusters specific Kubernetes version

### ISSUE THREAD

**Issue by dipankardas011** [kubesimplify/ksctl#104]
# Why do we need it?
it will provide flexibility to choose between the various Kubernetes version

# What will it bring?
anyone can choose between the Kubernetes version

**Comment by Horiodino** [comment]
hey @dipankardas011  can you give more info , this issue looks entrusting

**Comment by dipankardas011** [comment]
> hey @dipankardas011 can you give more info , this issue looks entrusting

currently we have planned to add it in the redegin phase

**Comment by ashutosh887** [comment]
@dipankardas011 
I would like to work on this.. Please assign

**Comment by dipankardas011** [comment]
> @dipankardas011 
> I would like to work on this.. Please assign 

Currently we are planning to abstract these functionality of the kubeadm and k3s so that its more streamline

You can check it here #111

**Comment by dipankardas011** [comment]
@ashutosh887 thanks for showing your interest in working on this
Currently as core ksctl is done I have added .Version() for managed clusters to get the version for use and .Version() for the Distribution Factory as well

I have left a few TODOs as well if you are interested you can help us with that 😄

**Comment by dipankardas011** [comment]
once the PR #123 is merged to main branch you can start
