### ISSUE TITLE
[CLI,API](Local) Add Logging to the commandline for easy debugging

### ISSUE THREAD

**Issue by dipankardas011** [kubesimplify/ksctl#11]

**Comment by Gauravkumar2701** [comment]
Hi @dipankardas011  I would like to work on this issue if anyone not working on this.

**Comment by dipankardas011** [comment]
> Hi @dipankardas011  I would like to work on this issue if anyone not working on this.

Yes you can

**Comment by Gauravkumar2701** [comment]
@dipankardas011 so what are the required can you please elaborate it.

**Comment by Gauravkumar2701** [comment]
@dipankardas011  so what are the requirement can you please elaborate it. Should I implement this logging capability in all the provider or specific provider etc or whether for only specific commands or feature.

**Comment by Gauravkumar2701** [comment]
Hi @dipankardas011 I am waiting for you reply.

**Comment by dipankardas011** [comment]
@AvineshTripathi please give him context

**Comment by Gauravkumar2701** [comment]
@AvineshTripathi I am waiting for your explanation so that I can proceed further.

**Comment by dipankardas011** [comment]
@Gauravkumar2701 this pr will help us to make a single module which upon calling will print according without us calling fmt printing or log printing each time with some styling

**Comment by dipankardas011** [comment]
@Gauravkumar2701 sorry for the delayed response

**Comment by dipankardas011** [comment]
@Gauravkumar2701 you can also take a look this particular issue #22
It's similar

**Comment by dipankardas011** [comment]
@Gauravkumar2701 Yes it's more about organising and reducing the repetation and making to more consistent
