### ISSUE TITLE
feature(Release): Chocolatey based Package distribution

### ISSUE THREAD

**Issue by MRafaydev** [kubesimplify/ksctl#110]
# Why do we need it?

The purpose of this enhancement is to create a Chocolatey package for the ksctl CLI tool. Currently, there is no Chocolatey package available for easy installation and management of ksctl. By creating a Chocolatey package, we can provide a convenient way for users to install and update ksctl on Windows systems using the Chocolatey package manager.

# What it will bring?

**Creating a Chocolatey package for ksctl will bring the following benefits:**

1. Simplified installation: Users will be able to install ksctl with a single command using Chocolatey, eliminating the need for manual downloads and configurations.
2. Easy updates: With the Chocolatey package, users can easily update ksctl to the latest version by running a simple command, ensuring they have access to the latest features and bug fixes.
3. Consistency: A Chocolatey package will provide a standardized installation method across Windows systems, ensuring that users have a consistent experience when installing ksctl.
4. Integration with existing workflows: Many users already utilize Chocolatey for managing software packages on their Windows machines. By offering a Chocolatey package, ksctl can integrate seamlessly into their existing workflows and package management systems.

**Current Progress:**

1. Created pkg folder.
2. Inside the pkg folder, created the choco folder.
3. Inside the choco folder, created the chocolateyinstall.ps1 script.
4. Created the ksctl.nuspec file.

**Challenges Faced:**
At this stage, I encountered the following challenge:

I need to provide the URL for the build release of the ksctl .exe file to include in the Chocolatey package.
Currently, I don't have the .exe file, as it needs to be downloaded during the package installation from the internet.

**Required Guidance:**
I am seeking guidance on the following steps to proceed:

1. Building the ksctl CLI binary and generating the .exe file.
2. Publishing the ksctl CLI binary as a release and obtaining the download URL.
3. Updating the chocolateyinstall.ps1 script with the correct URL for the ksctl binary.
4. Any additional steps required to successfully create the Chocolatey package.

**chocolateyinstall.ps1** 

<img width="958" alt="image" src="https://github.com/kubesimplify/ksctl/assets/66843891/b2b9fb77-5225-4ac9-b9b5-29793cfbba27">

**ksctl.nuspec**

<img width="960" alt="image" src="https://github.com/kubesimplify/ksctl/assets/66843891/fddb3bf7-7c90-4b7f-8f0b-bbcc0c93d46b">

**Comment by dipankardas011** [comment]
It's a feature request
@AvineshTripathi and I will review and tell you👍

**Comment by dipankardas011** [comment]
For the url you can check out the install.ps1 script how it attains it

**Comment by AvineshTripathi** [comment]
@dipankardas011 do you think there is requirement having a dir structure as mentioned above, why not keeping this in root ?

**Comment by dipankardas011** [comment]
> @dipankardas011 do you think there is requirement having a dir structure as mentioned above, why not keeping this in root ?

@MRafaydev does pkg thing required or is it more towards the project structuring?

**Comment by MRafaydev** [comment]
> > @dipankardas011 do you think there is requirement having a dir structure as mentioned above, why not keeping this in root ?
> 
> @MRafaydev does pkg/ dir required or is it more towards the project structuring?

This is more towards the project structuring like if we add more others packages in future like for brew etc. So it is better we have the separation of packages that's why i have created this folder structure. But we can also add in the root folder. .

**Comment by dipankardas011** [comment]
For me 👍
@AvineshTripathi ?

**Comment by MRafaydev** [comment]
Hey @dipankardas011 we have any update on this ? So I try the binary file with choco.

**Comment by dipankardas011** [comment]
> Hey @dipankardas011 we have any update on this ? So I try the binary file with choco.

Yes you can start

**Comment by dipankardas011** [comment]
> Hello @dipankardas011, I was wondering when the binary package for ksctl will be released. We need to define the URL of the binary package in Chocolatey (choco). Could you please provide an update on the release schedule for ksctl binary package? Thank you!

Release does have windows binary
