### ISSUE TITLE
enhancement: Migration to a new architecture

### ISSUE THREAD

**Issue by dipankardas011** [kubesimplify/ksctl#111]
# Why do we need it?
able to abstract the API continents like the cloud provider into a `ksctl engine` and have another `k8s distribution engine` to lower the coupling between API and cli 

# What it will bring?
- easier addition of more cloud providers
- generalization of the API folder to be able to make it more user-friendly to use as RestAPI

cc @AvineshTripathi 

Closes  #88 

# Note
currently the development will be done on branch `111-feature-migration-to-new-architecture`

This branch should not be closed

**Comment by dipankardas011** [comment]
If anyone want to join us, you can talk with us

**Comment by MRafaydev** [comment]
Hey @dipankardas011, I'm excited to collaborate on this project!

**Comment by NimishKashyap** [comment]
I'm also excited to contribute to this project!

**Comment by dipankardas011** [comment]
> Hey @dipankardas011   for handling different providers, we can follow the patterns followed by ORMs like GORM right?
> 
> So basically, we'll have a common API interface which will be implemented in each provider sdk. and that sdk will be downloaded separately depending upon the provider, following an adapter+strategy based pattern.
> 
> Similar to pattern of GORM / Terraform, where we download the common sdk + one provider sdk. Is it a correct way to think about the architecture?

@AvineshTripathi

**Comment by dipankardas011** [comment]
It's great to see you all eager to help 😀

**Comment by yashgangwar7558** [comment]
Hey @dipankardas011, I am interested in working on this project

**Comment by dipankardas011** [comment]
let us know if their are any difficulties you are facing to understand

**Comment by MRafaydev** [comment]
> Hey @dipankardas011, I am interested in working on this project

Noted

> @MRafaydev @NimishKashyap @yashgangwar7558 do provide your proposal on what all subsection you all want to contribute

Noted.

**Comment by MRafaydev** [comment]
> @MRafaydev @NimishKashyap @yashgangwar7558 do provide your proposal on what all subsection you all want to contribute

Noted.

**Comment by yashgangwar7558** [comment]
> @MRafaydev @NimishKashyap @yashgangwar7558 do provide your proposal on what all subsection you all want to contribute

I am just getting started with ksctl and exploring the project and code. I would like to work on the provider section but have no experience so needed help to get started.

**Comment by dipankardas011** [comment]
> > @MRafaydev @NimishKashyap @yashgangwar7558 do provide your proposal on what all subsection you all want to contribute
> 
> I am just getting started with ksctl and exploring the project and code. I would like to work on the provider section but have no experience so needed help to get started.

good to know your focus point

**Comment by dipankardas011** [comment]
> > @MRafaydev @NimishKashyap @yashgangwar7558 do provide your proposal on what all subsection you all want to contribute
> 
> I am just getting started with ksctl and exploring the project and code. I would like to work on the provider section but have no experience so needed help to get started.

📓 noted!!

**Comment by dipankardas011** [comment]
have you all joined the kubesimplify discord server?
if not do join so that I can easily arrange the meet link and details

**Comment by MRafaydev** [comment]
> have you all joined the kubesimplify discord server? if not do join so that I can easily arrange the meet link and other issue details

Hey @dipankardas011, I was thinking it would be great if we could schedule a weekly development meeting. It would provide us with a dedicated time to discuss our progress, address any challenges, and align our efforts. Let me know what you think!

**Comment by dipankardas011** [comment]
> > have you all joined the kubesimplify discord server? if not do join so that I can easily arrange the meet link and other issue details
> 
> Hey @dipankardas011, I was thinking it would be great if we could schedule a weekly development meeting. It would provide us with a dedicated time to discuss our progress, address any challenges, and align our efforts. Let me know what you think!

Thanks for suggesting will surely do that
Will fix the date and time after some of us have joined

**Comment by dipankardas011** [comment]
## 🔗 Issues status
- [ ] #122
- [ ] #104 
- [ ] #88
- [ ] #87 
- [ ] #80

**Comment by dipankardas011** [comment]
> ##  Issues status
> * [ ]  [bug: ksctl delete-cluster Region Validation failed #122](https://github.com/kubesimplify/ksctl/issues/122)
> * [ ]  [enhancement: support to create clusters specific Kubernetes version #104](https://github.com/kubesimplify/ksctl/issues/104)
> * [ ]  [enhancement: Inclusion of Strategy Pattern for API #88](https://github.com/kubesimplify/ksctl/issues/88)
> * [ ]  [enhancement: Add firewall rules for the HA cluster on various providers #87](https://github.com/kubesimplify/ksctl/issues/87)
> * [ ]  [enhancement: Add a lock on the config files during write operation #80](https://github.com/kubesimplify/ksctl/issues/80)

Here is the reference for us @AvineshTripathi for these Issue to be resolved along side the PR

**Comment by dipankardas011** [comment]
I have thought of this variable to decide whether the previous steps were completed
if its still "Building" and user requests to try again for creation it will resume from where its done 
and id the status is "DONE" then controller will through an error

for all these we need to make the load() request from storage interface and if it has found the cluster folder
it means 2 things either it was successful or it had some interrupt

Its still an idea would need some feedbacks

it solves the state issue of interrupt either Keyboard or network or database issue in provider
and then user can delete based on that he or she things

its much like terraform (as far as I know)

![image](https://github.com/kubesimplify/ksctl/assets/65275144/dda9ea0a-8734-4cd4-9d36-65943d3aac66)

**Comment by dipankardas011** [comment]
also current changes suggest

- `Engine.go` should contain the `Cloud`, `Storage`, `Distribution` interfaces
- `Manager` object will be created for the cli to interact
- `Manager` is the controller of flow of instructions
- `Manager` so it can call `cloudController` and `kubernetesController` based on requ
-

**Comment by dipankardas011** [comment]
> ## State management by the storageController
> I have thought of this variable to decide whether the previous steps were completed if its still "Building" and user requests to try again for creation it will resume from where its done and id the status is "DONE" then controller will through an error
> 
> for all these we need to make the load() request from storage interface and if it has found the cluster folder it means 2 things either it was successful or it had some interrupt
> 
> Its still an idea would need some feedbacks
> 
> it solves the state issue of interrupt either Keyboard or network or database issue in provider and then user can delete based on that he or she things
> 
> its much like terraform (as far as I know)
> 
> ![image](https://user-images.githubusercontent.com/65275144/258416491-dda9ea0a-8734-4cd4-9d36-65943d3aac66.png)

Current open for feedbacks

**Comment by dipankardas011** [comment]
Docs update and adding test cases is left
