### ISSUE TITLE
enhancement: migrate the usage guide section into getting started guide

### ISSUE THREAD

**Issue by YashPimple** [kubesimplify/ksctl#112]
# Why do we need it?
I went through the ksctl documentation and would like to discuss an issue so when we go through the getting started guide of [ksctl](https://kubesimplify.github.io/ksctl/docs/getting-started/install) it begins with steps of installing ksctl on different operating system alongside i would like to suggest can we also add section where we can explain about all the ksctl cli cmd inside the [Getting Started Section](https://kubesimplify.github.io/ksctl/docs/getting-started/install/) with a small demo rather than having a [usage guide](https://github.com/kubesimplify/ksctl/blob/main/USAGE.md) linked to readme file since it will help new contributor/users know how to proceed further with ksctl and it usage also maintaining a good documentation

# What it will bring?
It will greatly enhance the documentation by empowering new contributors and users to better understand and utilize ksctl, thereby promoting a smoother and more accessible experience.

# Additional Information
I am working on it.

**Comment by dipankardas011** [comment]
Closes #44
