### ISSUE TITLE
bug: Installation Video Not Working

### ISSUE THREAD

**Issue by SaarthakMaini** [kubesimplify/ksctl#115]
# Describe 🐞 

The Installation Video in the [Getting Started Section](https://kubesimplify.github.io/ksctl/docs/getting-started/install) is broken.

# Reproduce 💻 ➡️  💻 

- Go to the above mentioned link
- Scroll Down and try to play the `Installation Video`

# Possible Fix & Expected behavior🔧 

Needs Discussion
https://stackoverflow.com/questions/14079808/html5-video-is-not-playing-mp4-error-invalid-source/

# Screenshots :framed_picture:
![image](https://github.com/kubesimplify/ksctl/assets/94912101/a11b96b4-9a3c-41ac-9cd5-acb0642a8fb9)

**Comment by NayanPatidar** [comment]
#116 Hey this might solve the issue. Can you give it a check

**Comment by NayanPatidar** [comment]
https://github.com/kubesimplify/ksctl/pull/116#pullrequestreview-1473667573
I have made the changes again. Can you once again give it a check.

**Comment by HarshDeep61034** [comment]
After discussing with @NayanPatidar I'm creating the pull request as i have fixed this issue successfully and no one is Assigned.
