### ISSUE TITLE
bug: ksctl delete-cluster Region Validation failed

### ISSUE THREAD

**Issue by riteshsonawane1372** [kubesimplify/ksctl#122]
`ksctl delete-cluster civo -n testcluster -r LN01`

The cmd doesn't check if the region entered is valid or not "LN01" which is not a valid region. This will give an error that "cluster-name" doesn't exist. 
![image](https://github.com/kubesimplify/ksctl/assets/72307121/9d1227e8-b5d3-44e1-b3f2-a1b40273d6aa)

**Comment by dipankardas011** [comment]
@riteshsonawane1372 thanks for pointing it out

**Comment by dipankardas011** [comment]
Yes validation is missing!

**Comment by dipankardas011** [comment]
It will be addresed in the new redesign!

**Comment by dipankardas011** [comment]
@riteshsonawane1372 thanks for raising this issue
now it's resolved. during initializing of the state of each provider it validates them
