### ISSUE TITLE
enhancement: document on the various aspects of ksctl

### ISSUE THREAD

**Issue by dipankardas011** [kubesimplify/ksctl#129]
# Why do we need it?
Add the note to docs
- if the controlplane is dead what are the ways to recover it
- what are the different settings used(default)
- what all things ksctl doesn't manage

# What it will bring?

**Comment by 7h3-3mp7y-m4n** [comment]
hey , if the issue is still on then can I work on this ?

**Comment by dipankardas011** [comment]
yes

**Comment by dipankardas011** [comment]
@7h3-3mp7y-m4n I have assigned you

**Comment by 7h3-3mp7y-m4n** [comment]
thanks @dipankardas011

**Comment by saiyam1814** [comment]
@7h3-3mp7y-m4n have you started working on this ?

**Comment by dipankardas011** [comment]
> Hey, @saiyam1814, Yeah, I've been familiarizing myself with the `ksctl` environment. Sorry, I got caught in other activities. But I'll raise a PR very soon.

Sure @7h3-3mp7y-m4n but here is quick little update the website is not migrated to a new repo ksctl-docs Here is the new issue https://github.com/kubesimplify/ksctl-docs/issues/2
