### ISSUE TITLE
EP(website): add key features to the homepage

### ISSUE THREAD

**Issue by dipankardas011** [kubesimplify/ksctl#130]
# Why do we need it?
![image](https://github.com/kubesimplify/ksctl/assets/65275144/9c37e196-2dc6-46bf-88e7-34bf1566ae50)

replace it with key feature list
our is 'Lightweight', 'Fast', 'Customize'

Lightweight: it does not depends on any cli and hence its more is lightweight
Fast: it creates cluster within matters of seconds
Customize: customize all the aspects of cluster from size of nodes, k8s version, to pre-installed apps and many more

# What it will bring?
It will provide anyone what is the key benefits they would get from using ksctl

## Additional context

Check Contribution's guidelines

```[tasklist]
### Tasks
- [ ] Add corresponding images
```

**Comment by karnatisrinivas** [comment]
Hey @dipankardas011 , I would like to give it a try. Can you assign this to me?

**Comment by dipankardas011** [comment]
> Hey @dipankardas011 , I would like to give it a try. Can you assign this to me?

Done

**Comment by karnatisrinivas** [comment]
![image](https://github.com/kubesimplify/ksctl/assets/52213014/e4e6bad1-9d17-4869-b309-6b42bf88f179)

Correct me if I'm wrong @dipankardas011 , key features you mentioned are already present in docs, and I assumed to change them and also to add relevant images.

**Comment by dipankardas011** [comment]
Sorry forgot to change, the current issue requirement is to add new images which are relevant

**Comment by karnatisrinivas** [comment]
![image](https://github.com/kubesimplify/ksctl/assets/52213014/b37a74e0-1999-4267-9410-35d0dc1e6b83)

**Comment by dipankardas011** [comment]
> ![image](https://user-images.githubusercontent.com/52213014/261840312-b37a74e0-1999-4267-9410-35d0dc1e6b83.png)

looks good
