### ISSUE TITLE
enhancement(azure managed): Changes to the default OS security updates mechanism 

### ISSUE THREAD

**Issue by dipankardas011** [kubesimplify/ksctl#143]
# Why do we need it?
You're receiving this notice because you’re currently using Azure Kubernetes Service (AKS) and haven’t chosen an explicit OS security mechanism.

To avoid disruptions stemming from unmanaged Canonical nightly security updates, AKS will disable unmanaged Canonical nightly updates by 2 September 2023 on clusters that haven’t specified an update option explicitly, mapping to the option “None” in the node OS upgrade channel feature.
https://learn.microsoft.com/azure/aks/auto-upgrade-node-image

# What it will bring?
https://learn.microsoft.com/en-gb/azure/aks/auto-upgrade-node-image

## Additional context

Check [Contribution's guidelines](https://kubesimplify.github.io/ksctl/docs/contributions)

**Comment by ShivangShandilya** [comment]
@dipankardas011 I'm here finally!!
Starting off with `good-first-issues` would love to work on this and would also require your assistance too :smile:

**Comment by dipankardas011** [comment]
@ShivangShandilya are you working on this Issue?
