### ISSUE TITLE
docs: make accessing contribution guidelines easier

### ISSUE THREAD

**Issue by ShivangShandilya** [kubesimplify/ksctl#149]
# Why do we need it?
Instead of having this `The contents are moved to docs` in contributing.md file, we can link it to the correct destination [here](https://github.com/kubesimplify/ksctl/blob/main/website/docs/contributions.md) or we can directly link the same to the website.

![Screenshot from 2023-08-26 12-07-12](https://github.com/kubesimplify/ksctl/assets/101946115/2658a065-af27-4cb0-a68d-ea8dfb841a25)

# What it will bring?
Easier navigation to Contributing guide.

## Additional context

Check [Contribution's guidelines](https://kubesimplify.github.io/ksctl/docs/contributions)

**Comment by rj2704** [comment]
Hi @ShivangShandilya, I can fix this issue. Can you please assign this issue to me?

**Comment by ShivangShandilya** [comment]
> Hi @ShivangShandilya, I can fix this issue. Can you please assign this issue to me?

hey @rj2704 actually I don't even know if we need this or not, and if we do I was hoping to do a quick fix myself. Hope you understand :smile:

**Comment by rj2704** [comment]
Hi @ShivangShandilya no worries.

**Comment by dipankardas011** [comment]
how are you planning for this Issue still not clear and how will it improve?

**Comment by dipankardas011** [comment]
as this issue is not active I am closing it
feel free to reopen if the issue hasn't been resolved!
