### ISSUE TITLE
[API](Azure) Addition of AKS

### ISSUE THREAD

**Issue by dipankardas011** [kubesimplify/ksctl#16]
📖  Reference guide https://learn.microsoft.com/en-us/rest/api/aks/managed-clusters/

**Comment by dipankardas011** [comment]
https://github.com/Azure-Samples/azure-sdk-for-go-samples/tree/main/sdk/resourcemanager

**Comment by dipankardas011** [comment]
@AvineshTripathi ig this is the issue he have to work on?

**Comment by AvineshTripathi** [comment]
#64

**Comment by dipankardas011** [comment]
# Tasks :construction:
## maganed k8s support
- you might be taking a look Azure go sdk and also 
## HA k8s support
### Infrastructure procurement
- Resource Group
- 1 VM for database (choose the size most approproate for mysql)
- 1 VM for Loadbalancer also *ElasticIP* for it
- `n` VMs for controlplane nodes
- `m` VMs for workerplane nodes
- Security groups
- keypair

### Steps
**Step 1**: Create SSH keypair and upload
**Step 2**: Create Database VM and block all `incoming traffic` from outside world only allow incoming traffic from private IP and that to for Mysql port `3306`
**Step 3**: Create Loadbalancer VM and install HAproxy for configuring we nned the all the controlplane nodes private IPs and only allow `6443` port from anywhere
**Step 4**: Create Controlplane nodes and install k3s server with right set of ports ( Refer Kubernetes docs or K3s docs )and allow ports
**Step 5**: Create workerplane nodes and install k3s agents

### additional info
if possible make the worker nodes private VMs (no public IP)
if possible make the database private
worker nodes, database to be utilizing the initialization scripts (a.k.a. user-data script)
controlplane and loadbalancer will require ssh support to login and execute scripts

@AvineshTripathi

**Comment by dipankardas011** [comment]
## 🌐 Updates
 managed cluster is created ✔️

**Comment by dipankardas011** [comment]
## 🌐 Updates
 managed cluster is deleted ✔️ 
managed cluster fetch kubeconfig ✔️
managed cluster switch context ✔️
