### ISSUE TITLE
feature(Release): Arch based package distribution

### ISSUE THREAD

**Issue by dipankardas011** [kubesimplify/ksctl#182]
# Is your feature request related to a problem?📖
currently binary files are being distributed.

# Describe the solution you'd like 👨‍💻👩‍💻
NONE

# Describe alternatives you've considered💠

# Provider in question
- CLI

## Additional context
Check [Contribution's guidelines](https://kubesimplify.github.io/ksctl/docs/contributions)

**Comment by mihir1739** [comment]
Can I work on this. I've been using Arch for an year now and have a good understanding of pkgbuilds.

**Comment by dipankardas011** [comment]
@mihir1739 sure, thanks!

**Comment by dipankardas011** [comment]
Hi @mihir1739 on 15th Oct we have ksctl bi-weekly meet
