### ISSUE TITLE
[CLI] Use modern tools to make CLI beautiful

### ISSUE THREAD

**Issue by dipankardas011** [kubesimplify/ksctl#22]
Use modern tools to improve how CLI looks

**Comment by KlausMikhaelson** [comment]
Hey @dipankardas011 can I give this a try ? I haven't used go that much but I have used ts, js and many other languages so won't be that hard to give go a try ig

**Comment by dipankardas011** [comment]
@AvineshTripathi @kranurag7 what are your opinion

**Comment by dipankardas011** [comment]
We are planing to extend the cli interface to better one

**Comment by dipankardas011** [comment]
@KlausMikhaelson sure you can learn golang
Till then we can decide what to do😇
Hope it sounds good

**Comment by kranurag7** [comment]
@KlausMikhaelson for better look you can use any of the charm libraries. [bubbletea](https://github.com/charmbracelet/bubbletea) would be good but feel free to explore more.

**Comment by dipankardas011** [comment]
https://github.com/fatih/color

**Comment by Delta456** [comment]
You might like [Box CLI Maker](https://github.com/Delta456/box-cli-maker).

**Comment by dipankardas011** [comment]
@kranurag7 could we start to colorize cli?

**Comment by Vyom-Yadav** [comment]
@dipankardas011 I would like to work on this, I have experience working with golang and cli tools.

**Comment by dipankardas011** [comment]
Yes you can just have to wait till we plan what need to be added and removed for all the providers🙂
