### ISSUE TITLE
🐞 Bug: 'Contributing guide' link at CONTRIBUTING.md is broken

### ISSUE THREAD

**Issue by aj11anuj** [kubesimplify/ksctl#222]
# Describe 🐞
At bottom of ReadMe.md, there is a link for 'contributing guide' that is directing user to a CONTRIBUTING.md file and that file is redirecting to an error page due to broken link.

# Possible Fix 🔧

Update link at CONTRIBUTING.md file

**Comment by aj11anuj** [comment]
Can i raise a PR or do i have to wait for triage/accepted label?

**Comment by dipankardas011** [comment]
@aj11anuj yes you can resolve this issue
