### ISSUE TITLE
[Docs] Improve README.md

### ISSUE THREAD

**Issue by AvineshTripathi** [kubesimplify/ksctl#29]
Expected things in readme 

- Current Readme has some documents link which should remain in the updated version
- Description to the project
- working of the project
- scope of the project
- idea list 
- current roadmap
- Anything else which is necessary?

P.S. while taking up the issue make sure you share your thoughts for the same in the comments(we welcome new things in this if it matches our goal)

**Comment by dipankardas011** [comment]
Added #21

**Comment by siddhant-khisty** [comment]
Hi, I'd like to work on this. Could you please assign it to me?

**Comment by dipankardas011** [comment]
No package is needed just want go and Docker(local clusters) installed

**Comment by dipankardas011** [comment]
You can work on it if comfortable you can ask doubt if any on ksctl channel in discord😇

**Comment by dipankardas011** [comment]
Tasks:
- Add GIFs for demos

**Comment by AvineshTripathi** [comment]
#44
