### ISSUE TITLE
[Feature] [CLI,API] (Civo, Local) Add macOS Support

### ISSUE THREAD

**Issue by dipankardas011** [kubesimplify/ksctl#30]
# What is the problem? Please describe.

```
macOS Support is not available
```
# Describe the solution you'd like

```
To Edit the file location used for config storage and then build executable according to platforms
```

# Describe alternatives you've considered

**Comment by AvineshTripathi** [comment]
@dipankardas011 Add description proper one

**Comment by dipankardas011** [comment]
@AvineshTripathi Test the main branch if all are working then close this issue

**Comment by dipankardas011** [comment]
If there is any Issue you can reopen this issue
