### ISSUE TITLE
[HA] [CLI,API] (Civo) Add High Availability K8s Cluster

### ISSUE THREAD

**Issue by dipankardas011** [kubesimplify/ksctl#36]
## Is your feature request related to a problem? Please describe.
user's don't have the freedom to choose when they want to have H.A. Cluster

## Describe the solution you'd like
* Create 2 or more VMs
* configure them
* join them
* Fetch Kubeconfig and change the crt files such that the API server is available through the public Loadbalancer

**Comment by shreemaan-abhishek** [comment]
@dipankardas011 (and other maintainers), a sincere feedback: please consider making the writeups (issues, PRs) more readable. 

- I can see `h1` headings being used everywhere. h1 should be used only for top-level headings.
- use back tick-based code blocks ("```" or "`") only where necessary. For normal text please avoid using them. When the text is too long in a line, the user has to scroll horizontally to read everything.
- Please make the labels consistent in terms of the casing. Ideally, everything should be lowercase with [kebab-casing](https://stackoverflow.com/questions/11273282/whats-the-name-for-hyphen-separated-case)

Following these would make things more neat and slick. And more readable.

Sorry if this sounds too harsh, I easily get affected with visual appearance while others might not even care :P

**Comment by dipankardas011** [comment]
@AvineshTripathi @kranurag7 how can be improve

**Comment by dipankardas011** [comment]
Thank you for your feedback

**Comment by dipankardas011** [comment]
Done
