### ISSUE TITLE
[API,CLI] Not taking multiple cluster names during creation and deletion 

### ISSUE THREAD

**Issue by KiranSatyaRaj** [kubesimplify/ksctl#39]
I executed a command to create a few demo clusters by providing multiple cluster names as arguments, but it created the single cluster provided as the first in the CLI, the same goes for the delete-cluster command as well tried to delete multiple clusters at the same time only the first cluster name provided was deleted, I'm not sure if that's how it works
`~ # ksctl create-cluster local -c demo3 demo4
Building...

To use this cluster set this environment variable

export KUBECONFIG='/root/.ksctl/config/local/demo3/config'

CREATED!
~ # ksctl get
[
  {
    "cluster_name": "demo3",
    "region": "N/A",
    "provider": "local"
  }
]
`

**Comment by dipankardas011** [comment]
@KiranSatyaRaj the create and delete are for single cluster so the above

**Comment by dipankardas011** [comment]
creating >1 clusters increase the complexity its more intutive to go by single cluster 
> If you have any suggestion we can discuss in the #ksctl  in kubesimplify discord channel

**Comment by dipankardas011** [comment]
@KiranSatyaRaj if issue is resolved then you can close it

**Comment by KiranSatyaRaj** [comment]
> @KiranSatyaRaj if issue is resolved then you can close it

I'll close this issue for now and get back to you on discord.
