### ISSUE TITLE
enhancement: Add a demo working of ksctl as a gif 

### ISSUE THREAD

**Issue by AvineshTripathi** [kubesimplify/ksctl#44]
We are looking for a gif that shows the demo of working of ksctl in the readme so that new contributors can get started easily 
What will that GIF consist of:
- ksctl installation process
- Adding credentials
- creating a cluster 

p.s. in addition to this we can also add the tree of file paths for configs/creds

**Comment by SD-13** [comment]
Hi @AvineshTripathi , Can I work on this? Thanks,

**Comment by siddhant-khisty** [comment]
Hey @SD-13, are you working on it? I can take it up if not.

**Comment by SD-13** [comment]
Hi @siddhant-khisty, for exams I was busy but now I have started working.

**Comment by siddhant-khisty** [comment]
cool 👍

**Comment by SD-13** [comment]
Hey @siddhant-khisty, feel free to take this issue. Just realized I will not be able to do this rn as I don't have access to civo (the one we support till now) for some reason. Thanks,

**Comment by siddhant-khisty** [comment]
sure.

Hey @AvineshTripathi, do you want the 3 steps mentioned in separate gifs, or in a single gif? IMO separate would be better otherwise it would become something like 1-2 min. Not sure if that length is supported for a gif

**Comment by AvineshTripathi** [comment]
I think 1 gif should be fine of 10 sec(fast forwarded) @siddhant-khisty

**Comment by siddhant-khisty** [comment]
hmm. Not sure if all the content will be clear within 10-20 seconds. I'll try something out and let's see if it looks good or not

**Comment by siddhant-khisty** [comment]
Hey, I don't think I will be able to do this. I'm having some weird login issues with my civo account. Will take this issue again if if it gets fixed. In the meantime, someone else is free to pick it up

**Comment by karnatisrinivas** [comment]
Hello @AvineshTripathi , Can I give it a try.

**Comment by dipankardas011** [comment]
@karnatisrinivas are you still working 😄

**Comment by karnatisrinivas** [comment]
> @karnatisrinivas are you still working 😄

No @dipankardas011 , The issue is free to pick up.

**Comment by Aman123lug** [comment]
@dipankardas011 if someone is not working in this issue i am going to add gifs for this..✌️

**Comment by dipankardas011** [comment]
> @dipankardas011 if someone is not working in this issue i am going to add gifs for this..v

sure you can start working on this

**Comment by dipankardas011** [comment]
@Aman123lug you can start as the CLI is almost stable

**Comment by Aman123lug** [comment]
@dipankardas011 thank you

**Comment by dipankardas011** [comment]
#112

**Comment by dipankardas011** [comment]
Added video files
