### ISSUE TITLE
[CLI,API] (ALL) Use `log` instead of `fmt`

### ISSUE THREAD

**Issue by dipankardas011** [kubesimplify/ksctl#46]
# Is your feature request related to a problem? Please describe.

```
use of fmt increases the redundancy and uniformatiy reduces
```
# Describe the solution you'd like

```
we can instead use log package wherever necessary / can be replaced
```

# Describe alternatives you've considered

```
if cannot replace it then format the fmt such that it has a better sense to users
```

**Comment by dipankardas011** [comment]
## Its a Call for Proposal
if any one wants to work on this they must inform in this Issue then only create a PR

**Comment by dipankardas011** [comment]
# Linked Issue
- [ ] #11

**Comment by legendarykamal** [comment]
hi @dipankardas011 can I work on this ?

**Comment by dipankardas011** [comment]
yes, you can work but we are planning to more beautify using some printer utility package in the api package
@kranurag7 has suggested some you he might brief about it more

**Comment by dipankardas011** [comment]
- https://github.com/kubesimplify/ksctl/issues/22

**Comment by dipankardas011** [comment]
so the current status of it is:
- ha-civo has the log as printing method
- civo managed cluster will require the `log`
- local cluster is lagging with the `log`
      i can provide more info regarding it if you want

**Comment by dipankardas011** [comment]
@legendarykamal you can check the api/printer

**Comment by dipankardas011** [comment]
so you need to check the api folder as well as cli folder and check what all log are required to be added in the printer folder

if you wish you can talk with the assigned person of Issue #22

**Comment by dipankardas011** [comment]
because you both will be editing the printer folder!

**Comment by dipankardas011** [comment]
if you both have any doubt feel free to communicate here or in the discord channel of kubesimplify with channel #ksctl

**Comment by legendarykamal** [comment]
sure thanks for the upfront help @dipankardas011

**Comment by dipankardas011** [comment]
@legendarykamal are you working on this issue?
