### ISSUE TITLE
[API][HA](*) Fix code scanning alert - Use of insecure HostKeyCallback implementation

### ISSUE THREAD

**Issue by dipankardas011** [kubesimplify/ksctl#47]
as the current implementation is using insecure HostKey option if shouldn't be used in production

Tracking issue for:
- [x] https://github.com/kubesimplify/ksctl/security/code-scanning/4

**Comment by dipankardas011** [comment]
https://github.com/kubesimplify/ksctl/blob/ae13930bb00db9156835879f66c3aaa271ded6cd/api/ha_civo/utils.go#L212

https://github.com/kubesimplify/ksctl/blob/ae13930bb00db9156835879f66c3aaa271ded6cd/api/ha_civo/utils.go#L264

**Comment by AvineshTripathi** [comment]
Add description

**Comment by dipankardas011** [comment]
@AvineshTripathi  added

**Comment by dipankardas011** [comment]
Generation of chatgpt
```go
package main

import (
	"fmt"
	"golang.org/x/crypto/ssh"
	"io/ioutil"
	"log"
	"net"
)

func main() {
	// Read the private key file
	key, err := ioutil.ReadFile("/path/to/private/key")
	if err != nil {
		log.Fatal(err)
	}
	// Create the Signer for the private key
	signer, err := ssh.ParsePrivateKey(key)
	if err != nil {
		log.Fatal(err)
	}
	// Read the expected host key file
	hostKey, err := ioutil.ReadFile("/path/to/expected/host/key")
	if err != nil {
		log.Fatal(err)
	}
	// Create the host key signer
	hostSigner, err := ssh.ParsePrivateKey(hostKey)
	if err != nil {
		log.Fatal(err)
	}
	// Create the SSH config with the signer and host key signer
	config := &ssh.ClientConfig{
		User: "user",
		Auth: []ssh.AuthMethod{
			ssh.PublicKeys(signer),
		},
		HostKeyCallback: ssh.FixedHostKey(hostSigner.PublicKey()),
	}
	// Connect to the SSH server
	conn, err := ssh.Dial("tcp", "publicIP:22", config)
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close()
	// Use the connection
	session, err := conn.NewSession()
	if err != nil {
		log.Fatal(err)
	}
	defer session.Close()
	// Run a command on the remote server
	output, err := session.CombinedOutput("ls -l")
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(string(output))
}
```

**Comment by dipankardas011** [comment]
then i guess we have to use ssh key instead of passwords
anyone can fix and all the same

**Comment by riteshsonawane1372** [comment]
assign me

**Comment by dipankardas011** [comment]
@riteshsonawane1372 you can discuss how we can move forward before you open the PR 😃

**Comment by dipankardas011** [comment]
you can refer to the Issue #61

**Comment by dipankardas011** [comment]
if you want any help do share

**Comment by riteshsonawane1372** [comment]
> if you want any help do share

Sure!

**Comment by dipankardas011** [comment]
@riteshsonawane1372 we will work on the Issue #61 there we will make a new PR 
I will be sharing the steps how we will go about addition of the SSH keypair

**Comment by dipankardas011** [comment]
@riteshsonawane1372 are you willing to continue working on this PR i have made the SSH keypair as default

**Comment by riteshsonawane1372** [comment]
Yes, I want to work on this PR due my end sem going on I'm not able work on it

**Comment by dipankardas011** [comment]
> Yes, I want to work on this PR due my end sem going on I'm not able work on it 

Sure best of luck for exam

**Comment by riteshsonawane1372** [comment]
@dipankardas011 tell me what changes to be made

**Comment by dipankardas011** [comment]
present in the  api/utils/main.go
