### ISSUE TITLE
enhancement: What is best way to save and rotate the kubeconfig

### ISSUE THREAD

**Issue by dipankardas011** [kubesimplify/ksctl#5]
I think we should stick to ~/.kube/config directory as kubectl and other tools read the kubeconfig file from this directory only. It might be a pain point for user to manage multiple kubeconfig at different location. Give user an option so that he can save and merge something like civo.

and what happens when we switch context using the command line and how it will handle

**Comment by dipankardas011** [comment]
The export command is redundant so if it can be automated

**Comment by dipankardas011** [comment]
The os.setenv not working in api section

**Comment by dipankardas011** [comment]
https://github.com/kubesimplify/ksctl/blob/main/src/api/civo/main.go#L153-L156

**Comment by saiyam1814** [comment]
the default should be to get merged with ~/.kube/config and then spit the output with kubectl context switch command. 
There should be an option to save it to a different location as well.

**Comment by dipankardas011** [comment]
@saiyam1814 this is the solution?
https://medium.com/@jacobtomlinson/how-to-merge-kubernetes-kubectl-config-files-737b61bd517d

**Comment by dipankardas011** [comment]
https://github.com/kubernetes-sigs/kind/blob/main/pkg/cluster/internal/kubeconfig/internal/kubeconfig/merge.go
https://github.com/kubernetes-sigs/kind/tree/main/pkg/cluster/internal/kubeconfig/internal/kubeconfig

**Comment by dipankardas011** [comment]
As it is no longer needed.
Thanks for all of your participation
