### ISSUE TITLE
enhancement(API): Return an error when fetching API key

### ISSUE THREAD

**Issue by Delta456** [kubesimplify/ksctl#55]
The function `fetchAPIKey` also needs to return an `err` along with a `string` because there can be errors when the `syscall` cannot open the file due to some permission issue.

The rewritten function would be:

```go
// fetchAPIKey returns the API key from the cred/civo file store
func fetchAPIKey() (err, string) {

	file, err := os.ReadFile(util.GetPathCIVO(0))
	if err != nil {
		return err, ""
	}
	if len(file) == 0 {
		return errors.New("Len of file is zero"), ""
	}

	return nil, strings.Split(string(file), " ")[1]
}
```

**Comment by bishal7679** [comment]
I would like to work on this good first issue
@dipankardas011 could you tell me here we should return an error message with `errors.New()` in 
err!=nil section along with "" as it is??

**Comment by dipankardas011** [comment]
You can use fmt.errorf
As the entire repo uses this only

**Comment by bishal7679** [comment]
> You can use fmt.errorf As the entire repo uses this only

ooh you mean fmt.errorf() instead of errors.New() in err!=nil section??

**Comment by bishal7679** [comment]
@dipankardas011 assign me this !

**Comment by dipankardas011** [comment]
yes

**Comment by dipankardas011** [comment]
@bishal7679 just wait till the current #59 gets merged as it is blocking this issue

**Comment by bishal7679** [comment]
> @bishal7679 just wait till the current #59 gets merged as it is blocking this issue

okay!

**Comment by dipankardas011** [comment]
@bishal7679 do check #6

**Comment by AvineshTripathi** [comment]
@lavakush07 you can raise up PR for this

**Comment by rakshitgondwal** [comment]
Hey!! Can I take this one up if no one is working on it right now?

**Comment by dipankardas011** [comment]
I think @lavakush07 is working on this

**Comment by dipankardas011** [comment]
Stale
