### ISSUE TITLE
[API](*) Option to AUTH without using `ksctl cred` instead using ENV VAR

### ISSUE THREAD

**Issue by dipankardas011** [kubesimplify/ksctl#6]
## Task
Create a hierarchy of authentication methods
1. Check if specific providers Environment variables have values in them
2. If not then go for standard or present method to read from `~/.ksctl/cred/*.json`

**Comment by dipankardas011** [comment]
@kranurag7 can you add it to the getCred() function

**Comment by dipankardas011** [comment]
we can decide upon the ENV VAR naming

**Comment by dipankardas011** [comment]
also @AvineshTripathi if you have any suggestions

**Comment by akshat5302** [comment]
Hey, @dipankardas011 I would like to work on this issue could you assign it to me?

**Comment by dipankardas011** [comment]
@akshat5302 before you continue we should discuss what environment var names to consider

**Comment by akshat5302** [comment]
Ok, and I have gone through docs to understand it better. I have one question do we have any standups or meetings where I can understand the project more clearly and ask my doubts as well

**Comment by dipankardas011** [comment]
We are yet to decide on this but you can raise your request in ksctl we maintainer we decide and fix the timing then

**Comment by akshat5302** [comment]
ok let us discuss env var names and what should be their tasks
What's on your mind?

**Comment by dipankardas011** [comment]
@kranurag7

**Comment by dipankardas011** [comment]
CIVO_API?

**Comment by dipankardas011** [comment]
or CIVO_TOKEN or CIVO_API_KEY?

**Comment by kranurag7** [comment]
`CIVO_TOKEN` sounds good to me. 
The flow should be like this. 
If `CIVO_TOKEN` env variable is set then proceed with this one, if not then read `~/.civo.json` file for apikey and again if not present show the prompt for entering the apikey.

**Comment by saiyam1814** [comment]
CIVO_TOKEN is official that is used with terraform and civo cli  and lets use that only

**Comment by akshat5302** [comment]
ok so this CIVO_TOKEN is to set with what values
Like 
os.Setenv(key,value)  
where key=CIVO_TOKEN
value= user_apikey(according to me)

**Comment by dipankardas011** [comment]
first os.Getenv(CIVO_TOKEN) if "" then try to read file ~/.civo.json if error notfound then prompt for api key

**Comment by akshat5302** [comment]
Ok got it 👍🏻

**Comment by akshat5302** [comment]
Should I have to create a new func for that in code??

**Comment by akshat5302** [comment]
Hey, @dipankardas011 waiting for your reply.

**Comment by dipankardas011** [comment]
If you have the civo cli installed it stores the cred in ~/.civo.json

Priority list | from
-|-
1 | environment var
2 | civo.json
3 | from ksctl cred civo

**Comment by dipankardas011** [comment]
@akshat5302 are you working on this issue?

**Comment by akshat5302** [comment]
Yes @dipankardas011 I just have to read the issue again will do it today

**Comment by Manda-supraja26** [comment]
I would like to know if my approach is correct or not.

```
// validating whether CIVO_TOKEN is set or not.
civoToken := os.Getenv("CIVO_TOKEN")
if civoToken != ""{
     return civoToken,nil
}

apikey ,err := fetchAPIKey(){
      if  err != nill{
              return "",err
        }

return apikey,nil

}




```

**Comment by dipankardas011** [comment]
Better if we can include the get environment inside the `fetchAPIkey()`

**Comment by Manda-supraja26** [comment]
Does this work ?
 if yes , can i create a pull request for this issue?
cause @akshat5302  is working on this.
``` 
func authenticate() (string, error) {
apikey ,err := fetchAPIKey(){
      if  err != nill{
              return "",err
        }
      civoToken := os.Getenv("CIVO_TOKEN")
      if civoToken != ""{
              return civoToken,nil
       }

return apikey,nil
}
```

**Comment by akshat5302** [comment]
You can work on it go ahead 👌

**Comment by dipankardas011** [comment]
@akshat5302 or @Manda-supraja26 if anyone of you interested to added the ENV var support to the azure provider as well?

**Comment by akshat5302** [comment]
Ok @dipankardas011

**Comment by akshat5302** [comment]
But I'm not that good at going and @Manda-supraja26 I guess had good knowledge of it. So it would be great if he/she takes the issue and I will help him/her or we can schedule a meeting as well to get this done together

**Comment by Manda-supraja26** [comment]
@dipankardas011  In the Azure folder, I didn't find any fetchAPIKey functions. should add one. and what should I consider? Environment variable: AZURE_TOKEN or any recommendations.

**Comment by dipankardas011** [comment]
> @dipankardas011  In the Azure folder, I didn't find any fetchAPIKey function. should add one. and what should I consider? Environment variable: AZURE_TOKEN or any recommendations.

https://github.com/kubesimplify/ksctl/blob/9957b38985b680069dae9c393f4ecefaf1795f60/api/azure/utils.go#L851
there you go

it basically read the secret keys from the file and makes sets the required environment variable its different from environment vairbale defined under bash script scope as child only inherts from parent not vise versa so inside the go process the env vars are accessable not outside that (Its just the explaination for you)

**Comment by dipankardas011** [comment]
> @dipankardas011  In the Azure folder, I didn't find any fetchAPIKey function. should add one. and what should I consider? Environment variable: AZURE_TOKEN or any recommendations.

@AvineshTripathi suggest some good names for the environment variables

**Comment by Manda-supraja26** [comment]
> > @dipankardas011  In the Azure folder, I didn't find any fetchAPIKey function. should add one. and what should I consider? Environment variable: AZURE_TOKEN or any recommendations.
> 
> https://github.com/kubesimplify/ksctl/blob/9957b38985b680069dae9c393f4ecefaf1795f60/api/azure/utils.go#L851
> 
> 
> there you go
> it basically read the secret keys from the file and makes sets the required environment variable its different from environment vairbale defined under bash script scope as child only inherts from parent not vise versa so inside the go process the env vars are accessable not outside that (Its just the explaination for you)

Thank you for the explanation.
