### ISSUE TITLE
Bash Auto-Completion 

### ISSUE THREAD

**Issue by riteshsonawane1372** [kubesimplify/ksctl#68]
# Is your feature request related to a problem?📖 

Auto Completion is not enable 

# Describe the solution you'd like 👨‍💻👩‍💻

Adding the Generated File to ~/.ksctl/config and then source it in /.bashrc 
`` rootCmd.GenBashCompletionFile("auto-completion.sh")``

# Describe alternatives you've considered💠

**Comment by riteshsonawane1372** [comment]
``
touch ${HOME}/.ksctl/cmd-completion.sh``
``cp auto-completion.sh ${HOME}/.ksctl/cmd-completion.sh``
``echo "source ${HOME}/.ksctl/cmd-completion.sh" >> ${HOME}/.bashrc``
``source ${HOME}/.bashrc``

Only the source ${Home}/.bashrc not working 
I need to manually type it in terminal, after that auto-completion works good

**Comment by kranurag7** [comment]
@riteshsonawane1372 Have you tried `source <(ksctl completion <shell>)`? 
Change the shell as per the shell you're using. 
If you want this to be persistent then please save this in your shell config file `(~/.bashrc, ~/.zshrc or ~/.config/fish/config.fish)`
