### ISSUE TITLE
[BUG][API] (*) ReadCredential panic

### ISSUE THREAD

**Issue by dipankardas011** [kubesimplify/ksctl#77]
# Describe 🐞 

panic in reading the credentials from user input

# Reproduce 💻 ➡️  💻 

try 
```bash
ksctl cred
```

# Possible Fix & Expected behavior🔧 

https://github.com/kubesimplify/ksctl/blob/9957b38985b680069dae9c393f4ecefaf1795f60/api/utils/main.go#L438
```diff
- 	bytePassword, err := terminal.ReadPassword(0)
- 	bytePassword, err := terminal.ReadPassword(<something which both the os support>)
```
0 -> means stdin in linux and osx

# Screenshots :framed_picture:

![image](https://user-images.githubusercontent.com/65275144/226171418-6685c33f-59a7-4ff4-8ab5-0ae36bb0bc93.png)

**Desktop (please complete the following information):**
 - OS
   - [ ] MacOS
   - [x] Windows
   - [ ] Linux
 - ksctl version `1.0.1-rc1`

# Additional context
Here is a releated issue - https://github.com/golang/go/issues/11914

**Comment by rakshitgondwal** [comment]
Would replacing `0` with `syscall.Stdin` work? I just tried it on linux and it works. @dipankardas011

**Comment by dipankardas011** [comment]
> Would replacing `0` with `syscall.Stdin` work? I just tried it on linux and it works. @dipankardas011 
> 

Have you tried in Windows?
Linux is okay the problem lies qith windows 😃

**Comment by rakshitgondwal** [comment]
I am not being able to set up ksctl locally on windows. Also, `syscall.Stdin` won't work I guess as `terminal.ReadPassword(fd int)` expects an int value in the argument. `int(syscall.Stdin)` would work but not really sure as I haven't tested it myself. @dipankardas011

**Comment by dipankardas011** [comment]
> I am not being able to set up ksctl locally on windows. Also, `syscall.Stdin` won't work I guess as `terminal.ReadPassword(fd int)` expects an int value in the argument. `int(syscall.Stdin)` would work but not really sure as I haven't tested it myself. @dipankardas011 

Use make install_windows something like that to install the cli in Windows environment

**Comment by rakshitgondwal** [comment]
> 
> Use make install_windows something like that to install the cli in Windows environment

I used `./builder.ps1`. But after that, it says
```
 `Run the following command as administrator: setx PATH "$env:path;C:\Users\Rakshit Gondwal\AppData\Local\ksctl" -m` 
```

I tried to run this command on powershell by running it as admin and it says
```
WARNING: The data being saved is truncated to 1024 characters.

SUCCESS: Specified value was saved.
```

now while trying to run `ksctl cred` it is still giving me 

```
ksctl : The term 'ksctl' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ksctl cred
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (ksctl:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by dipankardas011** [comment]
> > Use make install_windows something like that to install the cli in Windows environment
> 
> I used `./builder.ps1`. But after that, it says
> 
> ```
>  `Run the following command as administrator: setx PATH "$env:path;C:\Users\Rakshit Gondwal\AppData\Local\ksctl" -m` 
> ```
> 
> I tried to run this command on powershell by running it as admin and it says
> 
> ```
> WARNING: The data being saved is truncated to 1024 characters.
> 
> SUCCESS: Specified value was saved.
> ```
> 
> now while trying to run `ksctl cred` it is still giving me
> 
> ```
> ksctl : The term 'ksctl' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
> the spelling of the name, or if a path was included, verify that the path is correct and try again.
> At line:1 char:1
> + ksctl cred
> + ~~~~~
>     + CategoryInfo          : ObjectNotFound: (ksctl:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> ```

It should work Try to exit out of all the powershell

**Comment by dipankardas011** [comment]
Nevertheless found the solution
```diff
-    bytePassword, err := terminal.ReadPassword(0)
+    bytePassword, err := terminal.ReadPassword(int(os.Stdin.Fd()))
```

**Comment by dipankardas011** [comment]
could you create a PR, will merge it soon

**Comment by dipankardas011** [comment]
> > Use make install_windows something like that to install the cli in Windows environment
> 
> I used `./builder.ps1`. But after that, it says
> 
> ```
>  `Run the following command as administrator: setx PATH "$env:path;C:\Users\Rakshit Gondwal\AppData\Local\ksctl" -m` 
> ```
> 
> I tried to run this command on powershell by running it as admin and it says
> 
> ```
> WARNING: The data being saved is truncated to 1024 characters.
> 
> SUCCESS: Specified value was saved.
> ```
> 
> now while trying to run `ksctl cred` it is still giving me
> 
> ```
> ksctl : The term 'ksctl' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
> the spelling of the name, or if a path was included, verify that the path is correct and try again.
> At line:1 char:1
> + ksctl cred
> + ~~~~~
>     + CategoryInfo          : ObjectNotFound: (ksctl:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> ```

we can talk on this in todays biweekly meet

**Comment by rakshitgondwal** [comment]
> could you create a PR, will merge it soon

sure I will

**Comment by rakshitgondwal** [comment]
@dipankardas011 can I get the link for the biweekly meet?

**Comment by dipankardas011** [comment]
> @dipankardas011 can I get the link for the biweekly meet?

It's in the pinned comment of ksctl channel

**Comment by dipankardas011** [comment]
https://docs.google.com/document/d/10xpOpqgJeDI6p71ErtA5q9Nnc7fAPVGxDvJ5IHQNooU/edit?usp=sharing
Agenda doc link
