### ISSUE TITLE
bug(api): Ksctl Cred accepting empty strings

### ISSUE THREAD

**Issue by riteshsonawane1372** [kubesimplify/ksctl#79]
# Describe 🐞 

``Login Success`` even if no values are passed 

# Reproduce 💻 ➡️  💻 

``ksctl cred``

# Possible Fix & Expected behavior🔧 

# Screenshots :framed_picture:

<pre>Enter your credentials
Enter your SUBSCRIPTION ID 👇
    Enter Secret-&gt; 
Enter your TENANT ID 👇
    Enter Secret-&gt; 
Enter your CLIENT ID 👇
    Enter Secret-&gt; 
Enter your CLIENT SECRET 👇
    Enter Secret-&gt; 
2023/03/20 07:48:56 💾 configuration
Login Success
</pre>

**Desktop (please complete the following information):**
 - OS
   - [x] MacOS
   - [x] Windows
   - [x] Linux
 - ksctl version `<Version>`

# Additional context

**Comment by AvineshTripathi** [comment]
I don't think there is way to find if given cred will get you a client of that particular provider. We should reconsider change the message to `added cred or something similar

**Comment by riteshsonawane1372** [comment]
How should I create a client, from default location(example ~/.aws/config) or env variable ?

**Comment by riteshsonawane1372** [comment]
Asking for aws

**Comment by dipankardas011** [comment]
Not required for aws as of now as it's development has not started

**Comment by dipankardas011** [comment]
Another bug 
- #77
Can anyone fix this as well as it's related

**Comment by dipankardas011** [comment]
> I don't think there is way to find if given cred will get you a client of that particular provider. We should reconsider change the message to `added cred or something similar

@riteshsonawane1372 when the user enters a string of len() == 0 make a `[WARN]` message saying the above

**Comment by dipankardas011** [comment]
@riteshsonawane1372 i have assigned you to this issue
