### ISSUE TITLE
enhancement: Inclusion of Strategy Pattern for API

### ISSUE THREAD

**Issue by NimishKashyap** [kubesimplify/ksctl#88]
# Is your feature request related to a problem?📖 
No.

# Describe the solution you'd like 👨‍💻👩‍💻
The project's aim is to have a single API that handles multiple K8s providers. 

I personally find that to be a great use-case for a **Strategy Design pattern** (multiple strategies can be utilized at run-time within the context). A single API struct with multiple providers implemented as a strategy can be a great way to make the application more extensible and easy to maintain.

Would like to see this pattern being incorporated into the project for easier maintenance and extensibility.

# Need opinion on this

**Comment by dipankardas011** [comment]
Thanks for your opinion 
Will mark it for project backlog

Currently the project is in it's early stages so I personally feel that it's quite challenging to come up with unified api struct as different providers have different Requirements
But yes will be thinking in future how to generalize and find patterns from other pending platform support aws and gcp
😉

**Comment by dipankardas011** [comment]
This Issue has been marked as lowest priority as of now

**Comment by NimishKashyap** [comment]
Alright!

**Comment by dipankardas011** [comment]
@NimishKashyap we have started to work on it
if you want to join us do comment on the linked issue

**Comment by NimishKashyap** [comment]
Absolutely!

**Comment by dipankardas011** [comment]
@NimishKashyap thanks for this issue. Now its structure is more logical and better

**Comment by dipankardas011** [comment]
You can reopen if your issues hasn't got resolved
