### ISSUE TITLE
feat(CLI / API):  while creating aks-cluster ask user for  number of nodes that he wanted according to there subscription

### ISSUE THREAD

**Issue by Horiodino** [kubesimplify/ksctl#98]
see as we use aks dashboard ,aks also ask for nomber of workernodes between 1- 1000

what you think ? @dipankardas011

**Comment by AvineshTripathi** [comment]
I think there are already flags for it https://github.com/kubesimplify/ksctl/blob/main/cli/cmd/createClusterAzure.go#L62

**Comment by Horiodino** [comment]
all right , thats good :)
